# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0015_auto_20180528_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 30, 17, 36, 7, 292222), verbose_name='Cumple'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='color_texto',
            field=models.CharField(default='Sin completar', max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='deceso_date',
            field=models.DateTimeField(blank=True, verbose_name='Deceso'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad_texto',
            field=models.IntegerField(default='0', verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_texto',
            field=models.CharField(default='Sin completar', max_length=30, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo_texto',
            field=models.CharField(default='Sin definir', max_length=10, verbose_name='Sexo'),
        ),
    ]
