# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0038_auto_20180612_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtarjeta',
            name='aplicacion_text',
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='aplicacion_text',
            field=models.ManyToManyField(to='evet.Producto'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 23, 52, 23, 589560), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 12, 23, 52, 23, 587304), null=True, verbose_name='Nacimiento'),
        ),
    ]
