# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0039_auto_20180612_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='aplicacion_text',
            field=models.ManyToManyField(to='evet.Producto', verbose_name='Aplicaciones'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 0, 23, 5, 95640), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 13, 0, 23, 5, 93396), null=True, verbose_name='Nacimiento'),
        ),
    ]
