# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_texto', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('direccion_texto', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('codigopostal_texto', models.IntegerField(verbose_name='Codigo Postal')),
                ('tel_texto', models.CharField(max_length=40, verbose_name='Telefono')),
                ('celular_texto', models.CharField(max_length=40, verbose_name='Celular')),
                ('mail_texto', models.CharField(max_length=200, verbose_name='Email')),
                ('inscripcion_date', models.DateField(verbose_name='Fecha de inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizada', models.DateTimeField(default=datetime.datetime(2018, 6, 18, 22, 42, 43, 949169), verbose_name='Fecha y Hora')),
                ('peso_texto', models.FloatField(verbose_name='Peso')),
                ('temperatura_texto', models.FloatField(verbose_name='Temperatura')),
                ('frecuencia_respiratoria_texto', models.FloatField(verbose_name='Frecuencia Respiratoria')),
                ('linfonodulos_texto', models.CharField(max_length=50, verbose_name='LFN')),
                ('frecuencia_cardiaca', models.FloatField(verbose_name='Frecuencia Cardiaca')),
                ('auscultacion_text', models.CharField(choices=[('Bradicardia', 'Bradicardia'), ('Normal', 'Normal'), ('Taquicardia', 'Taquicardia')], max_length=20, verbose_name='Auscultacion')),
                ('auscultacion_ritmo_text', models.CharField(choices=[('Normal', 'Normal'), ('Arritmico', 'Arritmico')], max_length=20, verbose_name='Auscultacion Ritmo')),
                ('auscultacion_sonidos_text', models.CharField(choices=[('Normal', 'Normal'), ('Disminuido', 'Disminuido'), ('Aumentado', 'Aumentado')], max_length=20, verbose_name='Auscultacion Sonidos')),
                ('soplo_text', models.CharField(choices=[('No detectado', 'No detectado'), ('1/6', '1/6'), ('2/6', '2/6'), ('3/6', '3/6'), ('4/6', '4/6'), ('5/6', '5/6'), ('6/6', '6/6')], max_length=20, verbose_name='Dimension')),
                ('enObservasion_bool', models.BooleanField(verbose_name='En Observaci\xf3n')),
                ('ficha', models.TextField(verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_texto', models.CharField(max_length=200, verbose_name='Nombre')),
                ('chip', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chip')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado?')),
                ('raza_texto', models.CharField(default='Sin completar', max_length=30, verbose_name='Raza')),
                ('color_texto', models.CharField(default='Sin completar', max_length=30, verbose_name='Color')),
                ('sexo_texto', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=15, verbose_name='Sexo')),
                ('birthday_date', models.DateField(blank=True, default=datetime.datetime(2018, 6, 18, 22, 42, 43, 945536), null=True, verbose_name='Nacimiento')),
                ('deceso_date', models.DateField(blank=True, null=True, verbose_name='Deceso')),
                ('causa_deceso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Causa del deceso')),
                ('ambiente', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('PH', 'PH'), ('Campo', 'Campo'), ('Calle', 'Calle')], default='Departamento', max_length=30, verbose_name='Ambiente')),
                ('alimentacion', models.CharField(choices=[('Balanceado', 'Balanceado'), ('Casero', 'Casero'), ('Medicado', 'Medicado')], default='Balanceado', max_length=15, verbose_name='Alimentacion')),
                ('medicado_observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacion')),
                ('alimentacion_frecuencia', models.IntegerField(default=0, verbose_name='Frecuencia de alimento por dia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Producto')),
                ('referencia', models.CharField(max_length=10, verbose_name='ID de Referencia')),
                ('tipo', models.CharField(choices=[('Vacuna', 'Vacuna'), ('Medicamento', 'Medicamento'), ('Otro Producto', 'Otro Producto')], max_length=25, verbose_name='Categoria')),
                ('proxima_aplicacion', models.IntegerField(blank=True, null=True, verbose_name='Proxima aplicaci\xf3n en dias')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Proxima visita')),
                ('razon', models.CharField(choices=[('Observacion', 'Observacion'), ('Vacuna', 'Vacuna'), ('Peluqueria', 'Peluqueria'), ('Operacion', 'Operacion')], default='Observacion', max_length=30, verbose_name='Razon')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
            ],
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='aplicacion_text',
            field=models.ManyToManyField(blank=True, null=True, to='evet.Producto', verbose_name='Aplicaciones'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='nombre_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='turno',
            field=models.ManyToManyField(to='evet.Turno', verbose_name='Turnos'),
        ),
    ]
