# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(verbose_name='Fecha de inscripcion'),
        ),
    ]
