# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0002_auto_20180510_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_texto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mail_texto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_texto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Documento_o_Pasaporte',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Domicilio',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Nombre_y_Apellido',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
