# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0008_auto_20180511_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
