# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0012_historialtarjeta_nombre_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtarjeta',
            name='nombre_owner',
        ),
    ]
