# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0014_auto_20180528_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtarjeta',
            name='circulatorio',
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='auscultacion_ritmo_text',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Arritmico', 'Arritmico')], default='Normal', max_length=20, verbose_name='Auscultacion Ritmo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='auscultacion_sonidos_text',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Disminuido', 'Disminuido'), ('Aumentado', 'Aumentado')], default='Normal', max_length=20, verbose_name='Auscultacion Sonidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='auscultacion_text',
            field=models.CharField(choices=[('Bradicardia', 'Bradicardia'), ('Normal', 'Normal'), ('Taquicardia', 'Taquicardia')], default='Normal', max_length=20, verbose_name='Auscultacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='frecuencia_cardiaca',
            field=models.FloatField(default=100, verbose_name='Frecuencia Cardiaca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='presencia_soplo_text',
            field=models.BooleanField(default=0, verbose_name='Presencia de Soplo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='soplo_text',
            field=models.CharField(choices=[('No detectado', 'No detectado'), ('1/6', '1/6'), ('2/6', '2/6'), ('3/6', '3/6'), ('4/6', '4/6'), ('5/6', '5/6'), ('6/6', '6/6')], default='No detectado', max_length=20, verbose_name='Dimension'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='ficha',
            field=models.TextField(verbose_name='Ficha'),
        ),
    ]
