# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0016_auto_20180530_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 30, 17, 38, 30, 170271), null=True, verbose_name='Cumple'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='deceso_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deceso'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
