# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0019_auto_20180604_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtarjeta',
            name='presencia_soplo_text',
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='enObservasion_bool',
            field=models.BooleanField(default=False, verbose_name='En Observaci\xf3n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='alimentacion',
            field=models.CharField(choices=[('Balanceado', 'Balanceado'), ('Casero', 'Casero'), ('Dieta', 'Dieta')], default='Balanceado', max_length=15, verbose_name='Alimentacion'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='alimentacion_frecuencia',
            field=models.IntegerField(default=0, verbose_name='Frecuencia de alimento por dia'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='ambiente',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('PH', 'PH'), ('Campo', 'Campo'), ('Calle', 'Calle')], default='Departamento', max_length=30, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 16, 21, 57, 745057), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 4, 16, 21, 57, 742684), null=True, verbose_name='Cumple'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo_texto',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=15, verbose_name='Sexo'),
        ),
    ]
