# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0020_auto_20180604_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad_texto',
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 16, 37, 59, 665578), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 4, 16, 37, 59, 664440), null=True, verbose_name='Cumple'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='deceso_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deceso'),
        ),
    ]
