# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0021_auto_20180604_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 19, 20, 0, 539001), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 5, 19, 20, 0, 537742), null=True, verbose_name='Cumple'),
        ),
    ]
