# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0024_auto_20180605_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 20, 22, 56, 743545), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 5, 20, 22, 56, 741143), null=True, verbose_name='Cumple'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_texto',
            field=models.CharField(max_length=30, verbose_name='Raza'),
        ),
    ]
