# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0025_auto_20180605_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='causa_deceso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Causa del deceso'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 21, 21, 7, 394890), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 5, 21, 21, 7, 392552), null=True, verbose_name='Cumple'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_texto',
            field=models.CharField(default='Sin completar', max_length=30, verbose_name='Raza'),
        ),
    ]
