# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0028_auto_20180607_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 7, 23, 26, 38, 728274), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='linfonodulos_texto',
            field=models.CharField(max_length=50, verbose_name='LFN'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 7, 23, 26, 38, 727065), null=True, verbose_name='Nacimiento'),
        ),
    ]
