# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0029_auto_20180607_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='chip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 1, 22, 5, 184018), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 11, 1, 22, 5, 181775), null=True, verbose_name='Nacimiento'),
        ),
    ]
