# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0031_auto_20180611_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_proxima_visita', models.DateField(blank=True, null=True, verbose_name='Fecha de proxima visita')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Producto')),
                ('referencia', models.CharField(max_length=10, verbose_name='ID de Referencia')),
                ('tipo', models.CharField(choices=[('Vacuna', 'Vacuna'), ('Medicamento', 'Medicamento'), ('Otro Producto', 'Otro Producto')], max_length=25, verbose_name='Categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 15, 28, 42, 286434), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 11, 15, 28, 42, 284021), null=True, verbose_name='Nacimiento'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='mascota_aplicada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota'),
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='nombre_aplicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Producto'),
        ),
    ]
