# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0041_auto_20180613_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Proxima visita')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
            ],
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 17, 4, 4, 889056), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 15, 17, 4, 4, 885578), null=True, verbose_name='Nacimiento'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='turno',
            field=models.ManyToManyField(to='evet.Turno', verbose_name='Turnos'),
        ),
    ]
