# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0044_auto_20180615_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 18, 2, 15, 55160), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 15, 18, 2, 15, 51859), null=True, verbose_name='Nacimiento'),
        ),
    ]
