# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0045_auto_20180615_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='razon',
            field=models.CharField(choices=[('Observacion', 'Observacion'), ('Vacuna', 'Vacuna'), ('Peluqueria', 'Peluqueria'), ('Operacion', 'Operacion')], default='Observacion', max_length=30, verbose_name='Razon'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 18, 22, 47, 49, 321006), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 18, 22, 47, 49, 317745), null=True, verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='esterilizado',
            field=models.BooleanField(default=False, verbose_name='Esterilizado?'),
        ),
    ]
