# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0046_auto_20180618_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 18, 29, 44, 279530), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 20, 18, 29, 44, 276608), null=True, verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proxima_aplicacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proxima aplicacion en dias'),
        ),
    ]
