# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 01:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0049_auto_20180621_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiosComplementarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 6, 21, 22, 32, 40, 499093), verbose_name='Fecha y hora')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Estudios Complementarios',
                'verbose_name_plural': 'Estudios Complementarios',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 21, 22, 32, 40, 470334), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='atendido_por',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='idvet'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 22, 32, 40, 475626), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 21, 22, 32, 40, 471921), null=True, verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_texto',
            field=models.CharField(max_length=200, verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Cliente', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='razon',
            field=models.CharField(choices=[('Observacion', 'Observacion'), ('Vacuna', 'Vacuna'), ('Peluqueria', 'Peluqueria'), ('Cirug\xeda', 'Cirug\xeda')], default='Observacion', max_length=30, verbose_name='Razon'),
        ),
    ]
