# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 01:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0051_auto_20180621_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudioscomplementarios',
            old_name='imagen',
            new_name='cardiologia',
        ),
        migrations.AddField(
            model_name='estudioscomplementarios',
            name='ecografia',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='estudioscomplementarios',
            name='radiografia',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 21, 22, 45, 33, 499244), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 22, 45, 33, 416929), verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 22, 45, 33, 523460), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 21, 22, 45, 33, 500874), null=True, verbose_name='Nacimiento'),
        ),
    ]
