# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0053_auto_20180622_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 22, 11, 10, 3, 726070), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 11, 10, 3, 643115), verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 11, 10, 3, 731085), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 22, 11, 10, 3, 727654), null=True, verbose_name='Nacimiento'),
        ),
    ]
