# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 20:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0055_auto_20180622_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudioscomplementarios',
            name='razon',
            field=models.CharField(choices=[('Radiografia', 'Radiografia'), ('Ecografia', 'Ecografia'), ('Electrocardiograma', 'Electrocardiograma'), ('Complementario', 'Complementario')], default='Complementario', max_length=30, verbose_name='Razon'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 22, 17, 31, 57, 871197), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 17, 31, 57, 906827), verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='radiografia',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 17, 31, 57, 877170), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 22, 17, 31, 57, 873232), null=True, verbose_name='Nacimiento'),
        ),
    ]
