# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0057_auto_20180622_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Nacimiento'),
        ),
    ]
