# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0058_auto_20180622_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='aplicacion_text',
            field=models.ManyToManyField(blank=True, to='evet.Producto', verbose_name='Aplicaciones'),
        ),
    ]
