# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_texto', models.CharField(max_length=200)),
                ('direccion_texto', models.CharField(max_length=200)),
                ('mail_texto', models.CharField(max_length=200)),
                ('inscripcion_date', models.DateTimeField(verbose_name='Fecha de inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_texto', models.CharField(max_length=200)),
                ('historial_texto', models.CharField(max_length=200)),
                ('diagnostico_texto', models.CharField(max_length=200)),
                ('inscripcion_date', models.DateTimeField(verbose_name='Fecha de inscripcion')),
                ('birthday_date', models.DateTimeField(verbose_name='Cumple')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Cliente')),
            ],
        ),
    ]
