# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0003_auto_20180510_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Documento_o_Pasaporte',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Domicilio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Nombre_y_Apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_texto',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_texto',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='mail_texto',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_texto',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
