# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0004_auto_20180510_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=500, verbose_name='Ficha')),
                ('fecha_realizada', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion_texto',
            field=models.CharField(max_length=200, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_texto',
            field=models.CharField(max_length=200, verbose_name='Documento o Pasaporte'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mail_texto',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_texto',
            field=models.CharField(max_length=200, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='diagnostico_texto',
            field=models.CharField(max_length=200, verbose_name='Diagnostico inicial'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='historial_texto',
            field=models.CharField(max_length=200, verbose_name='Historial clinico'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre_texto',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='nombre_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota'),
        ),
    ]
