# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0005_auto_20180511_0005'),
    ]

    operations = [

    ]