# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0010_auto_20180512_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
