# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0011_auto_20180512_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtarjeta',
            name='nombre_owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evet.Cliente'),
            preserve_default=False,
        ),
    ]
