# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0032_auto_20180611_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 15, 52, 29, 95227), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 11, 15, 52, 29, 93144), null=True, verbose_name='Nacimiento'),
        ),
    ]
