# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0035_auto_20180612_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacion',
            name='pet',
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='visita',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evet.HistorialTarjeta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 23, 37, 47, 397895), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 12, 23, 37, 47, 375907), null=True, verbose_name='Nacimiento'),
        ),
    ]
