# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0043_auto_20180615_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacion',
            name='nombre_aplicacion',
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='pet',
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 15, 17, 24, 43, 990964), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 15, 17, 24, 43, 989285), null=True, verbose_name='Nacimiento'),
        ),
        migrations.DeleteModel(
            name='Aplicacion',
        ),
    ]
