# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0048_auto_20180621_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='se_atiende',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota', verbose_name='Mascota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 21, 20, 1, 20, 518874), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 20, 1, 20, 521810), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 21, 20, 1, 20, 519833), null=True, verbose_name='Nacimiento'),
        ),
    ]
