# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0050_auto_20180621_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estudios_complementarios',
            field=models.ManyToManyField(to='evet.EstudiosComplementarios', verbose_name='Estudios Complementarios'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 21, 22, 35, 35, 473339), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 22, 35, 35, 384097), verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 22, 35, 35, 510040), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 21, 22, 35, 35, 474801), null=True, verbose_name='Nacimiento'),
        ),
    ]
