# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0054_auto_20180622_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtarjeta',
            name='estudios_complementarios',
        ),
        migrations.AddField(
            model_name='estudioscomplementarios',
            name='mascota',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota', verbose_name='Mascota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscripcion_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 22, 16, 2, 56, 10825), verbose_name='Fecha de inscripcion'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 16, 2, 56, 58131), verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='historialtarjeta',
            name='fecha_realizada',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 16, 2, 56, 15708), verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='birthday_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 22, 16, 2, 56, 12356), null=True, verbose_name='Nacimiento'),
        ),
    ]
