# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0059_auto_20180622_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='radiografia',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='estudioscomplementarios',
            name='razon',
            field=models.CharField(choices=[('Radiografia', 'Radiografia'), ('Ecografia', 'Ecografia'), ('Electrocardiograma', 'Electrocardiograma'), ('Estudios de laboratorio', 'Estudios de laboratorio')], default='Complementario', max_length=30, verbose_name='Razon'),
        ),
    ]
