# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-31 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_texto', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('direccion_texto', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('codigopostal_texto', models.IntegerField(blank=True, null=True, verbose_name='Codigo Postal')),
                ('tel_texto', models.CharField(blank=True, max_length=40, null=True, verbose_name='Telefono')),
                ('celular_texto', models.CharField(blank=True, max_length=40, null=True, verbose_name='Celular')),
                ('mail_texto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('inscripcion_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Especie')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiosComplementarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('razon', models.CharField(choices=[('Radiografia', 'Radiografia'), ('Ecografia', 'Ecografia'), ('Electrocardiograma', 'Electrocardiograma'), ('Estudios de laboratorio', 'Estudios de laboratorio'), ('Otros', 'Otros')], max_length=30, verbose_name='Razon')),
                ('radiografia', models.ImageField(blank=True, upload_to='images', verbose_name='Imagen')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='Archivo adjunto')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Informe')),
            ],
            options={
                'verbose_name': 'Estudio complementario',
                'verbose_name_plural': 'Estudios complementarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('peso_texto', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('temperatura_texto', models.FloatField(blank=True, null=True, verbose_name='Temperatura')),
                ('frecuencia_respiratoria_texto', models.FloatField(blank=True, null=True, verbose_name='Frecuencia Respiratoria')),
                ('linfonodulos_texto', models.CharField(blank=True, max_length=50, null=True, verbose_name='LFN')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Cardiaca')),
                ('auscultacion_text', models.CharField(blank=True, choices=[('Bradicardia', 'Bradicardia'), ('Normal', 'Normal'), ('Taquicardia', 'Taquicardia')], max_length=20, null=True, verbose_name='Auscultacion')),
                ('auscultacion_ritmo_text', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Arritmico', 'Arritmico')], max_length=20, null=True, verbose_name='Auscultacion Ritmo')),
                ('auscultacion_sonidos_text', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Disminuido', 'Disminuido'), ('Aumentado', 'Aumentado')], max_length=20, null=True, verbose_name='Auscultacion Sonidos')),
                ('soplo_text', models.CharField(blank=True, choices=[('No detectado', 'No detectado'), ('1/6', '1/6'), ('2/6', '2/6'), ('3/6', '3/6'), ('4/6', '4/6'), ('5/6', '5/6'), ('6/6', '6/6')], max_length=20, null=True, verbose_name='Dimension')),
                ('mucosa_text', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Palidas', 'Palidas'), ('Congestivas', 'Congestivas'), ('Ictericos', 'Ictericos')], max_length=20, null=True, verbose_name='Mucosa')),
                ('enObservasion_bool', models.BooleanField(verbose_name='En Observaci\xf3n')),
                ('ficha', models.TextField(verbose_name='Ficha')),
                ('atendido_por', models.IntegerField(blank=True, null=True, verbose_name='Identificacion')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_texto', models.CharField(max_length=200, verbose_name='Mascota')),
                ('chip', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chip')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado?')),
                ('color_texto', models.CharField(default='Sin completar', max_length=30, verbose_name='Color')),
                ('sexo_texto', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Sin Especificar', 'Sin Especificar')], default='Macho', max_length=15, verbose_name='Sexo')),
                ('birthday_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Nacimiento')),
                ('deceso_date', models.DateField(blank=True, null=True, verbose_name='Deceso')),
                ('causa_deceso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Causa del deceso')),
                ('ambiente', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('PH', 'PH'), ('Campo', 'Campo'), ('Calle', 'Calle')], default='Departamento', max_length=30, verbose_name='Ambiente')),
                ('alimentacion', models.CharField(choices=[('Balanceado', 'Balanceado'), ('Casero', 'Casero'), ('Medicado', 'Medicado')], default='Balanceado', max_length=15, verbose_name='Alimentacion')),
                ('medicado_observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacion')),
                ('alimentacion_frecuencia', models.IntegerField(default=0, verbose_name='Frecuencia de alimento por dia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Especie', verbose_name='Especie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Cliente', verbose_name='Responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Producto')),
                ('referencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID de Referencia')),
                ('tipo', models.CharField(choices=[('Vacuna', 'Vacuna'), ('Medicamento', 'Medicamento'), ('Otro Producto', 'Otro Producto')], max_length=25, verbose_name='Categoria')),
                ('proxima_aplicacion', models.IntegerField(verbose_name='Proxima aplicacion en dias')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Raza')),
                ('identificacion', models.CharField(max_length=25, verbose_name='Identificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Proxima visita')),
                ('razon', models.CharField(choices=[('Observacion', 'Observacion'), ('Vacuna', 'Vacuna'), ('Peluqueria', 'Peluqueria'), ('Cirug\xeda', 'Cirug\xeda'), ('Consulta', 'Consulta'), ('Especialidad', 'Especialidad'), ('Ecografia/Rayos', 'Ecografia/Rayos')], default='Observacion', max_length=30, verbose_name='Razon')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('se_atiende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota', verbose_name='Mascota')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza_texto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evet.Raza', verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='aplicacion_text',
            field=models.ManyToManyField(blank=True, to='evet.Producto', verbose_name='Aplicaciones'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='nombre_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota'),
        ),
        migrations.AddField(
            model_name='historialtarjeta',
            name='turno',
            field=models.ManyToManyField(to='evet.Turno', verbose_name='Turnos'),
        ),
        migrations.AddField(
            model_name='estudioscomplementarios',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evet.Mascota', verbose_name='Mascota'),
        ),
    ]
