# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evet', '0002_auto_20190606_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrostock',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
